[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    "@openzeppelin=lib/openzeppelin-contracts/"
]
fs_permissions = [{ access = "read", path = "./artifacts"}]

[fmt]
line_length = 100
# See more config options https://github.com/foundry-rs/foundry/tree/master/config