[profile.default]
src = 'src'
out = 'build/abis'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./"}]
test='test'
auto_detect_remappings=false


[fmt]
line_length = 100
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
