/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISTETH } from "./ISTETH";
export type { IUSDC } from "./IUSDC";
export type { IWETH } from "./IWETH";
export type { IWSTETH } from "./IWSTETH";
